// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v4.25.3
// source: grpc/metrics.proto

package grpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	MetricsService_Metrics_FullMethodName          = "/grpc.MetricsService/Metrics"
	MetricsService_GetMetricsStream_FullMethodName = "/grpc.MetricsService/GetMetricsStream"
)

// MetricsServiceClient is the client API for MetricsService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MetricsServiceClient interface {
	Metrics(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*MetricsAllResponse, error)
	GetMetricsStream(ctx context.Context, opts ...grpc.CallOption) (MetricsService_GetMetricsStreamClient, error)
}

type metricsServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMetricsServiceClient(cc grpc.ClientConnInterface) MetricsServiceClient {
	return &metricsServiceClient{cc}
}

func (c *metricsServiceClient) Metrics(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*MetricsAllResponse, error) {
	out := new(MetricsAllResponse)
	err := c.cc.Invoke(ctx, MetricsService_Metrics_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *metricsServiceClient) GetMetricsStream(ctx context.Context, opts ...grpc.CallOption) (MetricsService_GetMetricsStreamClient, error) {
	stream, err := c.cc.NewStream(ctx, &MetricsService_ServiceDesc.Streams[0], MetricsService_GetMetricsStream_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &metricsServiceGetMetricsStreamClient{stream}
	return x, nil
}

type MetricsService_GetMetricsStreamClient interface {
	Send(*MetricsData) error
	Recv() (*AskMetrics, error)
	grpc.ClientStream
}

type metricsServiceGetMetricsStreamClient struct {
	grpc.ClientStream
}

func (x *metricsServiceGetMetricsStreamClient) Send(m *MetricsData) error {
	return x.ClientStream.SendMsg(m)
}

func (x *metricsServiceGetMetricsStreamClient) Recv() (*AskMetrics, error) {
	m := new(AskMetrics)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// MetricsServiceServer is the server API for MetricsService service.
// All implementations must embed UnimplementedMetricsServiceServer
// for forward compatibility
type MetricsServiceServer interface {
	Metrics(context.Context, *Empty) (*MetricsAllResponse, error)
	GetMetricsStream(MetricsService_GetMetricsStreamServer) error
	mustEmbedUnimplementedMetricsServiceServer()
}

// UnimplementedMetricsServiceServer must be embedded to have forward compatible implementations.
type UnimplementedMetricsServiceServer struct {
}

func (UnimplementedMetricsServiceServer) Metrics(context.Context, *Empty) (*MetricsAllResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Metrics not implemented")
}
func (UnimplementedMetricsServiceServer) GetMetricsStream(MetricsService_GetMetricsStreamServer) error {
	return status.Errorf(codes.Unimplemented, "method GetMetricsStream not implemented")
}
func (UnimplementedMetricsServiceServer) mustEmbedUnimplementedMetricsServiceServer() {}

// UnsafeMetricsServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MetricsServiceServer will
// result in compilation errors.
type UnsafeMetricsServiceServer interface {
	mustEmbedUnimplementedMetricsServiceServer()
}

func RegisterMetricsServiceServer(s grpc.ServiceRegistrar, srv MetricsServiceServer) {
	s.RegisterService(&MetricsService_ServiceDesc, srv)
}

func _MetricsService_Metrics_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MetricsServiceServer).Metrics(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MetricsService_Metrics_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MetricsServiceServer).Metrics(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _MetricsService_GetMetricsStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(MetricsServiceServer).GetMetricsStream(&metricsServiceGetMetricsStreamServer{stream})
}

type MetricsService_GetMetricsStreamServer interface {
	Send(*AskMetrics) error
	Recv() (*MetricsData, error)
	grpc.ServerStream
}

type metricsServiceGetMetricsStreamServer struct {
	grpc.ServerStream
}

func (x *metricsServiceGetMetricsStreamServer) Send(m *AskMetrics) error {
	return x.ServerStream.SendMsg(m)
}

func (x *metricsServiceGetMetricsStreamServer) Recv() (*MetricsData, error) {
	m := new(MetricsData)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// MetricsService_ServiceDesc is the grpc.ServiceDesc for MetricsService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MetricsService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "grpc.MetricsService",
	HandlerType: (*MetricsServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Metrics",
			Handler:    _MetricsService_Metrics_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GetMetricsStream",
			Handler:       _MetricsService_GetMetricsStream_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "grpc/metrics.proto",
}
